language: go

sudo: required
dist: trusty

go:
 - "1.12.9"

install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo add-apt-repository ppa:pitti/systemd --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq upx systemd
  - sudo ./scripts/travis-install-rkt.sh
  - npm -g install bats

script:
  - ./gomake clean
  - ./gomake build
  - ./gomake test
  - ./gomake quality
  - ./gomake install
  - mkdir -p ~/.config/dgr
  - 'echo -e "rkt:\n pullPolicy: new" > ~/.config/dgr/config.yml'
  - sudo PATH=${GOPATH}/bin:$PATH ./examples/build.sh
