language: go

sudo: required
dist: trusty

go:
 - 1.6

install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo add-apt-repository ppa:duggan/bats --yes
  - curl -fsS --next file:///etc/os-release &>/dev/null || sudo add-apt-repository ppa:costamagnagianfranco/ettercap-stable-backports --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq upx curl
  - sudo ./scripts/travis-install-rkt.sh
  - sudo apt-get install -qq bats

script:
  - ./gomake clean build test quality install
  - sudo PATH=${GOPATH}/bin:$PATH ./examples/build.sh
