name: blablacar.github.io/dgr/aci-prometheus:0.16.1-1nerve2
aci:
  dependencies:
    - blablacar.github.io/dgr/aci-libc:1
  app:
    exec: [/prometheus/prometheus, -config.file, /etc/prometheus/prometheus.yml]
    mountPoints:
      - {name: data, path: /data, readOnly: false}
